### ISSUE TITLE
LOS indication colour gives different results at different resolutions

### ISSUE THREAD

**Issue by jammin84** [southern-wind/wind#67] opened 2016-03-21 02:21 UTC
LOS links are sometimes giving different positive or negative results based upon the image resolution.

The below screenshot shows exactly the same url except the width and height, but:
- one indicates "red" no LOS,
- one indicates "green" acceptable LOS.

![image](https://cloud.githubusercontent.com/assets/6802951/13909433/fceb651a-ef4d-11e5-95ba-33c50614b625.png)

Here are the direct links so you dont have to type it out.
- http://members.wafreenet.org/index.php/nodes/plot?a_node=1&b_node=2&frequency=5500&width=300&height=150
- http://members.wafreenet.org/index.php/nodes/plot?a_node=1&b_node=2&frequency=5500&width=570&height=250

**Comment by spinza** [comment] 2016-06-01 07:41
I had someone pointing out some LOS issues where he said it was clear that you could see the site but LOS said it's red.   

Example:
See: https://wind.ctwug.za.net/index.php/nodes?node=1616 
The first link listed is one of our best links.  When you increase size the link suddenly turns green:
Before:
https://wind.ctwug.za.net/index.php/nodes/plot?a_node=1616&b_node=333&frequency=5500&width=570&height=250
After:
https://wind.ctwug.za.net/index.php/nodes/plot?a_node=1616&b_node=333&frequency=5500&width=900&height=500

I would not have an idea how to find the cause.

**Comment by spinza** [comment] 2016-06-01 07:52
This is the code that detects whether the link should be red or green:
https://github.com/southern-wind/wind/blob/8b895ea17412f883d6e1c876de3c5dc378813363/globals/classes/geoimage.php#L109

**Comment by jammin84** [comment] 2016-06-01 08:16
hrmm.. looking at this again, looks like the antenna height changes between the 2 resolutions ... perhaps a drawing / padding error there somewhere?

**Comment by jammin84** [comment] 2016-06-01 08:20
Notice the AP on the right moves height just by adjusting the width 10px.

https://wind.ctwug.za.net/index.php/nodes/plot?a_node=1616&b_node=333&frequency=5500&width=570&height=250

https://wind.ctwug.za.net/index.php/nodes/plot?a_node=1616&b_node=333&frequency=5500&width=580&height=250

**Comment by spinza** [comment] 2016-06-01 08:39
I imagine it's rounding when making pixels.  The check for LOS is done at the pixel level.  And I'm pretty sure the check is most inaccurate over long links close to the antenna.  Because the pixels become bigger approximations of the terrain. 

Couple of simple solutions:
- Increase the resolution by 100% of the images but scale them down when showing by 50%?
- Ignore those checks close to the antenna?  Only make that code run a couple of pixels from the antenna either side or similar?  I.e. that loop becomes `for ($i=4;$i<$width-4;$i++) {` ..
- Combination of the above?

A better, more classy solution is to do "mathematical" checking of LOS separately.  This would involve some form of checking whether the line intercepts any of the elevations in between the sites.  A bit overkill I believe but theoretically interesting.

**Comment by jammin84** [comment] 2016-06-01 09:01
@spinza it was placing the AP at 2pixels in from the right edge of width rather than the final width/height location.  

My patch above fixes the issue to ensure its at the correct location.

But yes, I also agree that increasing drawing resolution and scaling would also improve the accuracy of this tool.

Bandwidth considerations are minimal.
2.3kb 500x250
4.8kb 1000x500

**Comment by spinza** [comment] 2016-06-23 07:33
Closed by #71

**Closed as completed by spinza** 2016-06-23 07:33 UTC
Labels: bug
